import Head from "next/head";
import Link from "next/link";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Services from "../components/Services/Services";
import Skills from "../components/Skills/Skills";
import Testimonials from "../components/Testimonials/Testimonials";
import Works from "../components/Works/Works";
import styles from "../styles/Home.module.css";
import { getContentFromMarkdown } from "../utils/getContentFromMarkdown";

export default function Home(props) {
  const { tel, email, content } = props.contactInfo;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <About />
        {/* <Link href={`/projects`}>projects Page</Link> */}
        <Skills />
        <Services />
        <Works />
        <Testimonials />
        <Contact />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const contactInfo = getContentFromMarkdown("contact");
  return {
    props: {
      contactInfo: contactInfo,
    },
  };
}
